CREATE DATABASE cheremiaka;

CREATE USER 'biba'@'localhost' IDENTIFIED BY 'Qwerty1-';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON cheremiaka.* TO 'biba'@'localhost';